language: java
jdk:
  - openjdk11
sudo: false
env:
  global:
    - # OSSRH_USER
    - secure: "iBhREAKe9rori2gk7UM8VkO9nVevniPRNrHRHNQh6+pofmp5Tswxf3lm6rIXmARJoJdyrQO3O2ZOYX3BOotmr85G+5CJQtPYy7BWyGMiP8dWbn5z0crNxdIjiyF9U4EFdfMiuO3Ys1rlpDjFkH0iYFwVwfDR3W0ySEWNP6zhU3A="
    - # OSSRH_PASSWORD
    - secure: "gVNhdL2ccZsy+fo1oEt18u7pwKjx55zA1QgGaELGZyo3VzjA1f1yHiCYHVYRMux/rIcKP1LvAHkMfGMiUP9fzpfvCDH0SRCEMTp7/1d9MR2uGBF590sqVB9S+GDwB5TGAVwFrqIxPE65Vl99Tv/WE95Ae0zONc8gtofJliMzPHA="
    - # GPG_KEY_NAME
    - secure: "mSQMmqojEQk4zBUf9k1sqn2llwGwS/zA/XwjETEIjshQH0rXbHnruMOCtwR53k21EOC9XMUr0UKrFRUyiy3Wb2ujmUNSapTsQDsTORgjLE/lMp6I5UcPU2Hi94B7tiJ10b/5NUDrmTbjx6qLe6ZWden2TAEQ3dEf8uMLl4VkGSM="
    - # GPG_PASSPHRASE
    - secure: "cienghDGHLBnoB+aIgD8f8gwFf1V1x+QCjqKLzu4DkDR/wTd+1zZhfz4ggWavo+CFqjHwAJ2S38WLzA15ENSs0sfe28Qp3eaCAYz7tg9LqHWWX53OQ/B8K8tVikMkrn+V1lztS0OxP3aacsch3MFl8CX5hOCpCm9T1WiIiy4vRI="

cache:
  directories:
    - $HOME/.m2

before_install:
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && openssl aes-256-cbc -K $encrypted_b6c74d7f8e86_key -iv $encrypted_b6c74d7f8e86_iv -in codesigning.asc.enc -out codesigning.asc -d"
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && gpg --fast-import codesigning.asc"

script: mvn clean verify ${TRAVIS_TAG:+-Drevision=${TRAVIS_TAG}}

after_success:
  - mvn jacoco:report coveralls:report
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DreposityId=sonatype-nexus-snapshots -Psign-artifacts -DskipTests --settings deploy-settings.xml"
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} != '' ]] && mvn deploy -DreposityId=sonatype-nexus-staging -Psign-artifacts -DskipTests -Drevision=${TRAVIS_TAG} --settings deploy-settings.xml"
